#!/bin/sh
echo "Is it morning ?"
read timeofday

if [ "$timeofday" = "yes" ]
then
    echo "Good morning"

elif [ "$timeofday" = "no" ]; then
    echo "Good afternoon"

else
    echo "Sorry, $timeofday not recognized"
fi
